// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

RWStructuredBuffer<int> data; 
RWStructuredBuffer<float3> keys;

float2 Resolution;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float key = data[id.x * Resolution.x + id.y];
    float3 color = keys[key];

    Result[id.xy] = float4(color, 0);
}
